export const NOTIF_TYPE = {
  ANNOUNCEMENT: "ANNOUNCEMENT",
  TENANT_RENT_BOOKING: "TENANT_RENT_BOOKING",
  TENANT_RENT_CONTRACT: "TENANT_RENT_CONTRACT",
  TENANT_RENT_CONTRACT_PAYMENT: "TENANT_RENT_CONTRACT_PAYMENT",
  TENANT_RENT_BILLING_REMINDER: "TENANT_RENT_BILLING_REMINDER"
};
export const NOTIF_TITLE = {
  TENANT_RENT_BOOKING_LEASED: "Tenant Rent Booking leased!",
  TENANT_RENT_BOOKING_CANCELLED: "Tenant Rent Booking cancelled!",
  TENANT_RENT_BOOKING_REJECTED: "Tenant Rent Booking rejected!",
  TENANT_RENT_BILLING_REMINDER: "Rent billing reminder!",
};
